sudo: required

services:
  - docker

before_install:
  - docker build -t oleg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true oleg/react-test npm test

after_success:
  - docker build -t oleg/multi-client ./client
  - docker build -t oleg/multi-nginx ./nginx
  - docker build -t oleg/multi-server ./server
  - docker build -t oleg/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push to dockerhub
  - docker push uhvatt/multi-client
  - docker push uhvatt/multi-nginx
  - docker push uhvatt/multi-server
  - docker push uhvatt/multi-worker



